apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: exam-davin
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http-nginx
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30443
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 30222
    - name: http-spring
      protocol: TCP
      port: 8080
      targetPort: 8080
